Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm_primeira_maquin"
    vb.memory = 1024
    vb.cpus = 2
  end
  # imagem usada
  config.vm.box = "hashicorp/bionic64"
  # configuracao de porta para o localhost
  config.vm.network "forwarded_port", guest: 80, host: 8090
  # placa de rede publica
  config.vm.network "public_network", ip:"192.168.1.55" 
  # Script externo
  config.vm.provision "shell", path: "nginx-install.sh"
  # sincronizando folders com a maquina remota
  config.vm.synced_folder "site/", "/var/www/html"
  #
  # Run Ansible from the Vagrant Host - Estudar e fazer projetos disso
  #
  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "playbook.yml"
  # end
end
