Vagrant.configure("2") do |config|
  # imagem usada
  config.vm.box = "hashicorp/bionic64"
  # configuracao de porta para o localhost
  config.vm.network "forwarded_port", guest: 80, host: 8090
  # placa de rede publica
  config.vm.network "public_network", ip:"192.168.1.55" 
  # Script externo
  config.vm.provision "shell", path: "nginx-install.sh"
  # sincronizando folders com a maquina remota
  config.vm.synced_folder "site/", "/var/www/html"
end
